### ISSUE TITLE
THIS IS FOR A HIGH SCHOOL PROJECT, DO NOW USE IT FOR REAL PURPOSES

### ISSUE THREAD

**Issue by batu-0** [smiling-developer/krypton#2]
this isnt professionaly developed, its just here for demonstration and experimentation purposes, do not use this for real life applications as it might contain critical vulnerabilities and its really unoptimized, just an early warning

**Comment by batu-0** [comment]
this issue wont be of any use so might as well close it

**Comment by smiling-developer** [comment]
i'll add that on README
